### PR TITLE
Do not add line numbers to extremely long feedback or code

### LINKED ISSUE #1210: The inspect submission view freezes in the browser if the feedback is excessively large
If a submission has excessively large feedback, e.g., a few megabytes of text, then loading the teacher's inspect submission page seems to freeze the web browser and fail to open the web page normally. However, when the full-view feedback page is opened, then rendering the page is not particularly slow and it works well. What makes these pages so different?

Both pages seem to render the feedback in the Django templates.
* https://github.com/apluslms/a-plus/blob/74ed233d372df3cbf664f4fb6e5aaa1b72b3f489/exercise/views.py#L441
* https://github.com/apluslms/a-plus/blob/74ed233d372df3cbf664f4fb6e5aaa1b72b3f489/exercise/templates/exercise/submission.html#L40
* https://github.com/apluslms/a-plus/blob/74ed233d372df3cbf664f4fb6e5aaa1b72b3f489/exercise/staff_views.py#L156
* https://github.com/apluslms/a-plus/blob/74ed233d372df3cbf664f4fb6e5aaa1b72b3f489/exercise/templates/exercise/staff/inspect_submission.html#L94
* https://github.com/apluslms/a-plus/blob/74ed233d372df3cbf664f4fb6e5aaa1b72b3f489/exercise/templates/exercise/staff/_assessment_panel.html#L165

However, the inspect page renders the feedback twice since it also inserts it into the form for editing the feedback.
https://github.com/apluslms/a-plus/blob/74ed233d372df3cbf664f4fb6e5aaa1b72b3f489/exercise/templates/exercise/staff/_assessment_panel.html#L67

The inspect page also loads the student's submitted files via AJAX in JavaScript code. If the submitted file is small in size, then that can't cause the page to freeze, right?
https://github.com/apluslms/a-plus/blob/74ed233d372df3cbf664f4fb6e5aaa1b72b3f489/exercise/static/exercise/assessment.js#L31

-------------------------------------------------------------------------------

This submission in a real course is an example of the problem. Opening the feedback page (the first link) works fine, but opening the inspect page does not (the second link).
* https://plus.cs.aalto.fi/tietotekniikka-sovelluksissa/2023/matlab2/tehtavat/matlab2_tehtavat_secant/submissions/6268153/
* https://plus.cs.aalto.fi/tietotekniikka-sovelluksissa/2023/matlab2/tehtavat/matlab2_tehtavat_secant/submissions/6268153/inspect/

### PR DESCRIPTION
**Pull request by ihalaij1**
# Description

**What?**

Previously, the inspect submission page froze if line numbers were added to extremely long feedback/code. Line numbers are now added only if the feedback or code is shorter than 5000 lines.

- A page with ~5000 lines of feedback takes about 3 seconds to load with line numbers.
- A page with ~230 000 lines of feedback used to freeze the page. Now it loads fine, but without line numbers.

Fixes #1210

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Tested that the inspect submission page no longer freezes.

**Did you test the changes in**

- [x] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

### CODE REVIEW

**Review by Mankro — APPROVED** [review]
Excellent!

File: assets/js/aplus.js [hunk 1]
```diff
@@ -331,14 +331,17 @@ $(function() {
...
+            // The for-loop can freeze the page if line numbers are added to extremely long feedback/code.
             const pre = $(codeBlock);
             const lines = pre.html().split(/\r\n|\r|\n/g);
-            const list = $("<table/>").addClass("src");
-            for (var i = 1; i <= lines.length; i++) {
-                list.append('<tr><td class="num unselectable">' + i + '</td><td class="src">' + lines[i - 1] + '</td></tr>');
+            if (lines.length < 5000) {
+              const list = $("<table/>").addClass("src");
+              for (var i = 1; i <= lines.length; i++) {
+                  list.append('<tr><td class="num unselectable">' + i + '</td><td class="src">' + lines[i - 1] + '</td></tr>');
```
Comment (Mankro) [inline assets/js/aplus.js:341]: This one line is indented with 4 spaces, but 2 is enough. :laughing:
